steps:

  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$REPO_NAME:$SHORT_SHA', '.']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$REPO_NAME:$SHORT_SHA']

  # Step 3: Deploy to Cloud Run with environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        SUPABASE_URL=$$(gcloud secrets versions access latest --secret=SUPABASE_URL_DEV_DEVIANTS)
        SUPABASE_SERVICE_ROLE_KEY=$$(gcloud secrets versions access latest --secret=SUPABASE_SERVICE_ROLE_KEY_DEV_DEVIANTS)
        
        echo "Deploying server with environment variables from Secret Manager"
        
        gcloud run deploy "$REPO_NAME" \
          --image "us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$REPO_NAME:$SHORT_SHA" \
          --region us-central1 \
          --port=8080 \
          --allow-unauthenticated \
          --cpu=1 \
          --cpu-boost \
          --execution-environment=gen2 \
          --min-instances=1 \
          --set-env-vars=SUPABASE_URL="$${SUPABASE_URL}",SUPABASE_SERVICE_ROLE_KEY="$${SUPABASE_SERVICE_ROLE_KEY}",ENABLE_SCHEDULER=true,USE_TIMEZONE_SCHEDULES=true,SPORT_SCHEDULES=seasonal

  # Step 4: Ensure Cloud Scheduler jobs exist (scale-up / scale-down)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        SERVICE_ACCOUNT="$PROJECT_NUMBER-compute@developer.gserviceaccount.com"

        echo "Creating or updating Cloud Scheduler jobs..."

        # Scale Up (20:00 UTC = 3PM ET)
        gcloud scheduler jobs create http scale-up-cron \
          --schedule "0 20 * * *" \
          --uri "https://us-central1-run.googleapis.com/apis/serving.knative.dev/v1/namespaces/$PROJECT_ID/services/$REPO_NAME" \
          --http-method PATCH \
          --oauth-service-account-email "$SERVICE_ACCOUNT" \
          --headers "Content-Type=application/merge-patch+json" \
          --message-body '{"spec":{"template":{"metadata":{"annotations":{"autoscaling.knative.dev/minScale":"1"}}}}}' \
          --location us-central1 || \
        gcloud scheduler jobs update http scale-up-cron \
          --schedule "0 20 * * *" \
          --uri "https://us-central1-run.googleapis.com/apis/serving.knative.dev/v1/namespaces/$PROJECT_ID/services/$REPO_NAME" \
          --http-method PATCH \
          --oauth-service-account-email "$SERVICE_ACCOUNT" \
          --headers "Content-Type=application/merge-patch+json" \
          --message-body '{"spec":{"template":{"metadata":{"annotations":{"autoscaling.knative.dev/minScale":"1"}}}}}' \
          --location us-central1

        # Scale Down (09:00 UTC = 1AM HT)
        gcloud scheduler jobs create http scale-down-cron \
          --schedule "0 12 * * *" \
          --uri "https://us-central1-run.googleapis.com/apis/serving.knative.dev/v1/namespaces/$PROJECT_ID/services/$REPO_NAME" \
          --http-method PATCH \
          --oauth-service-account-email "$SERVICE_ACCOUNT" \
          --headers "Content-Type=application/merge-patch+json" \
          --message-body '{"spec":{"template":{"metadata":{"annotations":{"autoscaling.knative.dev/minScale":"0"}}}}}' \
          --location us-central1 || \
        gcloud scheduler jobs update http scale-down-cron \
          --schedule "0 12 * * *" \
          --uri "https://us-central1-run.googleapis.com/apis/serving.knative.dev/v1/namespaces/$PROJECT_ID/services/$REPO_NAME" \
          --http-method PATCH \
          --oauth-service-account-email "$SERVICE_ACCOUNT" \
          --headers "Content-Type=application/merge-patch+json" \
          --message-body '{"spec":{"template":{"metadata":{"annotations":{"autoscaling.knative.dev/minScale":"0"}}}}}' \
          --location us-central1


images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$REPO_NAME:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

