steps:

  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$REPO_NAME:$SHORT_SHA', '.']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$REPO_NAME:$SHORT_SHA']

  # Step 3: Deploy to Cloud Run with environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        SUPABASE_URL=$$(gcloud secrets versions access latest --secret=SUPABASE_URL_DEV_DEVIANTS)
        SUPABASE_SERVICE_ROLE_KEY=$$(gcloud secrets versions access latest --secret=SUPABASE_SERVICE_ROLE_KEY_DEV_DEVIANTS)
        
        echo "Deploying server with environment variables from Secret Manager"
        
        gcloud run deploy "$REPO_NAME" \
          --image "us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$REPO_NAME:$SHORT_SHA" \
          --region us-central1 \
          --port=8080 \
          --allow-unauthenticated \
          --cpu=1 \
          --cpu-boost \
          --execution-environment=gen2 \
          --min-instances=1 \
          --set-env-vars=SUPABASE_URL="$${SUPABASE_URL}",SUPABASE_SERVICE_ROLE_KEY="$${SUPABASE_SERVICE_ROLE_KEY}",ENABLE_SCHEDULER=true,USE_TIMEZONE_SCHEDULES=true,SPORT_SCHEDULES=seasonal

  # Step 4: Apply Cloud Scheduler jobs (scale-up / scale-down)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        echo "Syncing Cloud Scheduler jobs from YAML..."
        
        # Scale Up job
        gcloud scheduler jobs create http scale-up-score-processors \
          --location=us-central1 \
          --quiet \
          --description="Scale up Cloud Run service at 3PM ET" \
          --schedule="$(yq '.schedule' scale-up-scheduler.yaml)" \
          --time-zone="$(yq '.timeZone' scale-up-scheduler.yaml)" \
          --uri="$(yq '.httpTarget.uri' scale-up-scheduler.yaml)" \
          --http-method="$(yq '.httpTarget.httpMethod' scale-up-scheduler.yaml)" \
          --oidc-service-account-email="$(yq '.httpTarget.oidcToken.serviceAccountEmail' scale-up-scheduler.yaml)" \
          --headers="$(yq '.httpTarget.headers | to_entries | map(.key + "=" + .value) | join(",")' scale-up-scheduler.yaml)" \
          --message-body="$(yq '.httpTarget.body' scale-up-scheduler.yaml)" \
          || \
        gcloud scheduler jobs update http scale-up-score-processors \
          --location=us-central1 \
          --schedule="$(yq '.schedule' scale-up-scheduler.yaml)" \
          --time-zone="$(yq '.timeZone' scale-up-scheduler.yaml)" \
          --uri="$(yq '.httpTarget.uri' scale-up-scheduler.yaml)" \
          --http-method="$(yq '.httpTarget.httpMethod' scale-up-scheduler.yaml)" \
          --oidc-service-account-email="$(yq '.httpTarget.oidcToken.serviceAccountEmail' scale-up-scheduler.yaml)" \
          --headers="$(yq '.httpTarget.headers | to_entries | map(.key + "=" + .value) | join(",")' scale-up-scheduler.yaml)" \
          --message-body="$(yq '.httpTarget.body' scale-up-scheduler.yaml)"
        
        # Scale Down job
        gcloud scheduler jobs create http scale-down-score-processors \
          --location=us-central1 \
          --quiet \
          --description="Scale down Cloud Run service at 1AM HT" \
          --schedule="$(yq '.schedule' scale-down-scheduler.yaml)" \
          --time-zone="$(yq '.timeZone' scale-down-scheduler.yaml)" \
          --uri="$(yq '.httpTarget.uri' scale-down-scheduler.yaml)" \
          --http-method="$(yq '.httpTarget.httpMethod' scale-down-scheduler.yaml)" \
          --oidc-service-account-email="$(yq '.httpTarget.oidcToken.serviceAccountEmail' scale-down-scheduler.yaml)" \
          --headers="$(yq '.httpTarget.headers | to_entries | map(.key + "=" + .value) | join(",")' scale-down-scheduler.yaml)" \
          --message-body="$(yq '.httpTarget.body' scale-down-scheduler.yaml)" \
          || \
        gcloud scheduler jobs update http scale-down-score-processors \
          --location=us-central1 \
          --schedule="$(yq '.schedule' scale-down-scheduler.yaml)" \
          --time-zone="$(yq '.timeZone' scale-down-scheduler.yaml)" \
          --uri="$(yq '.httpTarget.uri' scale-down-scheduler.yaml)" \
          --http-method="$(yq '.httpTarget.httpMethod' scale-down-scheduler.yaml)" \
          --oidc-service-account-email="$(yq '.httpTarget.oidcToken.serviceAccountEmail' scale-down-scheduler.yaml)" \
          --headers="$(yq '.httpTarget.headers | to_entries | map(.key + "=" + .value) | join(",")' scale-down-scheduler.yaml)" \
          --message-body="$(yq '.httpTarget.body' scale-down-scheduler.yaml)"


images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$REPO_NAME:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

