# docker-compose.yml - Example deployment configurations
version: '3.8'

services:
  # API server mode (default)
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - ALA_SCORE_PROCESSOR_SECRET=${ALA_SCORE_PROCESSOR_SECRET}
      - STATES=${STATES:-al}
      - SPORT=${SPORT:-football}
      - SCRAPE_CONCURRENCY=${SCRAPE_CONCURRENCY:-2}
      - ENABLE_SCHEDULER=false
    restart: unless-stopped

  # Scheduler mode - runs cron-like background tasks
  scheduler:
    build: .
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - ALA_SCORE_PROCESSOR_SECRET=${ALA_SCORE_PROCESSOR_SECRET}
      - STATES=${STATES:-al}
      - SPORT=${SPORT:-football}
      - SCRAPE_CONCURRENCY=${SCRAPE_CONCURRENCY:-2}
      - ENABLE_SCHEDULER=true
      - USE_TIMEZONE_SCHEDULES=${USE_TIMEZONE_SCHEDULES:-true}
      - SPORT_SCHEDULES=${SPORT_SCHEDULES:-seasonal}
    restart: unless-stopped
    
  # One-time CLI execution example
  # docker-compose run --rm cli scrape --states al,ga --sport football --force
  cli:
    build: .
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - ALA_SCORE_PROCESSOR_SECRET=${ALA_SCORE_PROCESSOR_SECRET}
    profiles:
      - cli
    entrypoint: ["python", "cli.py"]